### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by davecastlevania** [lucynaaleksandra/bwa-u4-feature-request#1]
<img width="678" alt="screen shot 2018-04-20 at 3 58 18 pm" src="https://user-images.githubusercontent.com/1700545/39071061-b2ff386a-44b3-11e8-84fb-9ce5eed8b015.png">

This Google Doc is private. Please make it public and resubmit your project repo so we can review. Thanks.

**Comment by lucynaaleksandra** [comment]
Dave, I just updated my permissions again... hope it works this time. thanks!
